---
- name: Base setup
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - vim
    - curl
    - telnet 
    - git
    - gnupg2
    - ca-certificates
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools